<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\BaseCrudController;use App\Http\Resources\ExamResource;use App\Models\Exam;use App\Services\Assessment\ExamService;use Illuminate\Http\Request;
class ExamController extends BaseCrudController{private const MODULE='Exams';private const RELATIONS=['assessmentType','academicYear','term','learningAreas'];public function __construct(private readonly ExamService$service){}
public function index(Request$r){$v=$r->validate(['academic_year_id'=>'sometimes|uuid','term_id'=>'sometimes|uuid','assessment_type_id'=>'sometimes|uuid','status'=>'sometimes|in:draft,published,closed','active'=>'sometimes|boolean','per_page'=>'sometimes|integer|min:1|max:100']);$q=Exam::with(self::RELATIONS)->current()->where('school_id',$this->school($r));foreach(['academic_year_id','term_id','assessment_type_id','status','active']as$f)$q->when(array_key_exists($f,$v),fn($x)=>$x->where($f,$v[$f]));return$this->success(ExamResource::collection($q->orderByDesc('start_date')->paginate($v['per_page']??20)),'Exams retrieved successfully.');}
public function show(Request$r,string$id){$e=$this->q($r)->with(self::RELATIONS)->find($id);return$e?$this->success(new ExamResource($e),'Exam retrieved successfully.'):$this->notFound('Exam not found.');}
public function store(Request$r){$v=$r->validate(['school_id'=>'sometimes|uuid|exists:schools,id','exam_name'=>'required|string|max:255','assessment_type_id'=>'required|uuid|exists:assessment_types,id','academic_year_id'=>'required|uuid|exists:academic_years,id','term_id'=>'required|uuid|exists:terms,id','start_date'=>'required|date','end_date'=>'required|date|after_or_equal:start_date','active'=>'sometimes|boolean','created_by'=>'sometimes|nullable|uuid|exists:users,id']);$e=$this->service->create($v,$this->school($r,$v),auth()->id());$this->audit($r,self::MODULE,'Create',$e,null,$e->toArray(),'Created exam.');return$this->created(new ExamResource($e->load(self::RELATIONS)),'Exam created successfully.');}
public function update(Request$r,string$id){$e=$this->q($r)->find($id);if(!$e)return$this->notFound('Exam not found.');$v=$r->validate(['exam_name'=>'sometimes|string|max:255','start_date'=>'sometimes|date','end_date'=>'sometimes|date','active'=>'sometimes|boolean','status'=>'sometimes|in:draft,published,closed']);if(isset($v['status'])&&$v['status']!==$e->status){$to=$v['status'];unset($v['status']);$this->service->transition($e,$to);}if($e->status!=='draft'&&array_intersect_key($v,array_flip(['exam_name','start_date','end_date'])))return$this->badRequest('Published or closed exam details cannot be changed.');$e->update($v);return$this->success(new ExamResource($e->refresh()->load(self::RELATIONS)),'Exam updated successfully.');}
public function destroy(Request$r,string$id){$e=$this->q($r)->find($id);if(!$e)return$this->notFound('Exam not found.');if($e->status!=='draft'||$e->learningAreas()->exists()||$e->results()->exists())return$this->badRequest('Only empty draft exams can be deleted.');$e->update(['active'=>false,'is_deleted'=>true,'deleted_at'=>now(),'deleted_by'=>auth()->id()]);return$this->success(null,'Exam deleted successfully.');}
private function q(Request$r){return Exam::current()->where('school_id',$this->school($r));}private function school(Request$r,array$v=[]):string{$id=$r->attributes->get('tenant_school_id')??$v['school_id']??$r->input('school_id');abort_if(!$id,403,'School context not found.');return(string)$id;}}
