<?php

return [
    'recent_auth_minutes' => 30,
    'heartbeat_stale_minutes' => 15,
    'backup_retention_days' => 30,
    'queue_warning_threshold' => 100,
    'failed_job_warning_threshold' => 10,
    'storage_warning_percentage' => 85,
    'restore_execution_enabled' => false,
    'backup_tooling' => 'manifest_only',
    'feature_flags' => [
        'administrator_portal_v2' => ['description' => 'Administrator operations portal', 'platform_only' => true],
        'parent_mobile_api' => ['description' => 'Parent mobile API access', 'school_overridable' => true],
        'teacher_mobile_api' => ['description' => 'Teacher mobile API access', 'school_overridable' => true],
        'learner_mobile_api' => ['description' => 'Learner mobile API access', 'school_overridable' => true],
        'online_elections' => ['description' => 'Online student elections', 'school_overridable' => true],
        'homework_portal' => ['description' => 'Homework portal features', 'school_overridable' => true],
    ],
    'provider_categories' => ['email', 'sms', 'push', 'payment', 'storage', 'webhook'],
    'provider_names' => [
        'email' => ['environment', 'log', 'resend'],
        'sms' => ['environment', 'fake', 'africas_talking'],
        'push' => ['environment', 'disabled', 'firebase'],
        'payment' => ['environment', 'fake', 'mpesa'],
        'storage' => ['environment', 'local_private'],
        'webhook' => ['environment', 'signed_http'],
    ],
    'queue_names' => ['default', 'communications', 'notifications', 'imports', 'reports', 'backups', 'webhooks'],
    'scheduler_tasks' => [
        'communications_dispatch' => 'communications:dispatch-scheduled',
        'admin_health' => 'admin-health:check',
        'admin_alerts' => 'admin-alerts:refresh',
        'admin_backup_dispatch' => 'admin-ops:backup-dispatch',
        'admin_backup_retention' => 'admin-ops:backup-retention',
        'admin_webhook_retry' => 'admin-ops:retry-webhooks',
        'admin_api_key_expiry' => 'admin-ops:expire-api-keys',
    ],
    'cache_groups' => ['school_configuration', 'permissions', 'dashboards', 'provider_readiness', 'reports', 'application'],
    'log_files' => ['application' => 'laravel.log'],
    'api_key_scopes' => ['school.read', 'users.read', 'communications.write', 'reports.read', 'webhooks.manage', 'platform.read'],
    'webhook_events' => ['communication.sent', 'communication.failed', 'payment.confirmed', 'payment.failed', 'report.published', 'learner.updated'],
    'backup_types' => ['database_metadata', 'database_logical', 'secure_file_manifest', 'configuration_manifest', 'full_platform'],
    'diagnostic_checks' => ['database', 'migrations', 'cache', 'queue', 'scheduler', 'storage', 'storage_link', 'providers', 'encryption', 'jwt', 'disk', 'failed_jobs'],
    'platform_settings' => [
        'default_timezone' => ['type' => 'timezone', 'default' => 'Africa/Nairobi'],
        'default_locale' => ['type' => 'string', 'default' => 'en'],
        'trial_length_days' => ['type' => 'integer', 'min' => 1, 'max' => 365, 'default' => 30],
        'grace_period_days' => ['type' => 'integer', 'min' => 0, 'max' => 90, 'default' => 7],
        'default_pagination' => ['type' => 'integer', 'min' => 10, 'max' => 100, 'default' => 25],
        'upload_limit_mb' => ['type' => 'integer', 'min' => 1, 'max' => 100, 'default' => 10],
        'device_limit' => ['type' => 'integer', 'min' => 1, 'max' => 20, 'default' => 5],
        'sync_limit' => ['type' => 'integer', 'min' => 10, 'max' => 1000, 'default' => 100],
        'queue_warning_threshold' => ['type' => 'integer', 'min' => 1, 'max' => 100000, 'default' => 100],
        'storage_warning_threshold' => ['type' => 'integer', 'min' => 50, 'max' => 99, 'default' => 85],
        'scheduler_stale_minutes' => ['type' => 'integer', 'min' => 5, 'max' => 1440, 'default' => 15],
        'backup_retention_days' => ['type' => 'integer', 'min' => 1, 'max' => 3650, 'default' => 30],
        'allowed_communication_channels' => ['type' => 'array', 'allowed' => ['in_app', 'email', 'sms'], 'default' => ['in_app', 'email']],
    ],
    'release' => [
        'version' => env('APP_VERSION', 'unversioned'),
        'build' => env('APP_BUILD', null),
        'released_at' => env('APP_RELEASED_AT', null),
    ],
];
